config/routes.rb
Rails.application.routes.draw do
  resources :game_logs
  get '/game_logs/game/:game_id' => 'game_logs#game', as: :game_logs_game #, constraints: { format: 'json' }

  resources :players

  resources :games
  get 'games/:id/dashboard' => 'games#dashboard', as: :game_dashboard

  resources :rounds

  resources :teams

  resources :tournaments

  resources :leagues

  devise_for :users

end

app/models/league.rb
class League < ActiveRecord::Base
  validates :name, presence: true

  has_many :tournaments
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :city)
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.haml
= simple_form_for(@league) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :city

  .form-actions
    = f.button :submit

app/views/leagues/edit.html.haml
%h1 Editing league

= render 'form'

= link_to 'Show', @league
\|
= link_to 'Back', leagues_path

app/views/leagues/index.html.haml
%h1 Listing leagues

%table.table.table-responsive.table-striped.table-bordered
  %thead.header-table
    %tr
      %th Name
      %th City
      %th
      %th
      %th

  %tbody
    - @leagues.each do |league|
      %tr
        %td= league.name
        %td= league.city
        %td= link_to 'Show', league
        %td= link_to 'Edit', edit_league_path(league)
        %td= link_to 'Destroy', league, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

= link_to 'New League', new_league_path

app/views/leagues/new.html.haml
%h1 New league

= render 'form'

= link_to 'Back', leagues_path

app/views/leagues/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @league.name
%p
  %b City:
  = @league.city

= link_to 'Edit', edit_league_path(@league)
\|
= link_to 'Back', leagues_path