config/routes.rb
Rails.application.routes.draw do
  resources :game_logs
  get '/game_logs/game/:game_id' => 'game_logs#game', as: :game_logs_game #, constraints: { format: 'json' }

  resources :players

  resources :games
  get 'games/:id/dashboard' => 'games#dashboard', as: :game_dashboard

  resources :rounds

  resources :teams

  resources :tournaments

  resources :leagues

  devise_for :users

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home, class_name: 'Team'
  belongs_to :visit, class_name: 'Team'
  belongs_to :round

  before_save :create_name
  before_validation :same_team

  STATUS = ['Scheduled', 'In Progress', 'Finished']

  private
    def create_name
      self.name = self.home.name+' vs '+self.visit.name
    end

    def same_team
      !(self.home == self.visit)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  layout 'ingame', only: [:dashboard]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    game = Game.find(params[:id])
    if game.status==Game::STATUS[1]
      #need to load the game
    else
      @game = game
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :home_id, :visit_id, :round_id, :game_date, :home_score, :visit_score)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= simple_form_for(@game) do |f|
  = f.error_notification

  .form-inputs
    = f.association :home
    = f.association :visit
    = f.association :round
    = f.input :game_date

  .form-actions
    = f.button :submit

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
\|
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1 Listing games

%table.table.table-responsive.table-striped.table-bordered
  %thead.header-table
    %tr
      %th Name
      %th Home
      %th Visit
      %th Game date
      %th Round
      %th Home score
      %th Visit score
      %th
      %th
      %th

  %tbody
    - @games.each do |game|
      %tr
        %td= game.name
        %td= game.home.name
        %td= game.visit.name
        %td= game.game_date
        %td= game.round.name
        %td= game.home_score
        %td= game.visit_score
        %td= link_to 'Show', game_dashboard_path(game.id)
        %td= link_to 'Edit', edit_game_path(game)
        %td= link_to 'Destroy', game, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Game', new_game_path

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @game.name
%p
  %b Home:
  = @game.home.name
%p
  %b Visit:
  = @game.visit.name
%p
  %b Game date:
  = @game.game_date
%p
  %b Home score:
  = @game.home_score
%p
  %b Visit score:
  = @game.visit_score

= link_to 'Edit', edit_game_path(@game)
\|
= link_to 'Back', games_path