config/routes.rb
Rails.application.routes.draw do
  resources :game_logs
  get '/game_logs/game/:game_id' => 'game_logs#game', as: :game_logs_game #, constraints: { format: 'json' }

  resources :players

  resources :games
  get 'games/:id/dashboard' => 'games#dashboard', as: :game_dashboard

  resources :rounds

  resources :teams

  resources :tournaments

  resources :leagues

  devise_for :users

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :team
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_url, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :active, :team_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= simple_form_for(@player) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :active
    = f.association :team

  .form-actions
    = f.button :submit

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1 Listing players

%table.table.table-responsive.table-striped.table-bordered
  %thead.header-table
    %tr
      %th Name
      %th Active
      %th Team
      %th Tournament
      %th
      %th
      %th

  %tbody
    - @players.each do |player|
      %tr
        %td= player.name
        %td= player.active
        %td= player.team.name
        %td= player.team.tournament.name
        %td= link_to 'Show', player
        %td= link_to 'Edit', edit_player_path(player)
        %td= link_to 'Destroy', player, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Player', new_player_path

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @player.name
%p
  %b Active:
  = @player.active
%p
  %b Team:
  = @player.team.name

= link_to 'Edit', edit_player_path(@player)
\|
= link_to 'Back', players_path