config/routes.rb
Rails.application.routes.draw do
  resources :game_logs
  get '/game_logs/game/:game_id' => 'game_logs#game', as: :game_logs_game #, constraints: { format: 'json' }

  resources :players

  resources :games
  get 'games/:id/dashboard' => 'games#dashboard', as: :game_dashboard

  resources :rounds

  resources :teams

  resources :tournaments

  resources :leagues

  devise_for :users

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Baskore
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          %a.navbar-brand Baskcore
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Tournament', tournaments_path
            %li
              = link_to 'Teams', teams_path
            %li
              = link_to 'Players', players_path
            %li
              = link_to 'Rounds', rounds_path
            %li
              = link_to 'Games', games_path
    %p.notice= notice
    %p.alert= alert
    .container-fluid
      .row
        .col-lg-12
          = yield

app/views/layouts/ingame.html.haml
!!!
%html
  %head
    %title Baskore - Game:
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{style:"line-height:1; background-color:black", oncontextmenu:"return false;"}
    %p.notice= notice
    %p.alert= alert
    = yield